Add http event field to store post body
aicers/giganto-client pull request #85
Opened 2023-11-21 14:05 UTC by jknpark

Refer to aicers/piglet#688

2023-11-22 01:08 UTC, syncpark requested changes

2023-11-22 01:08 UTC, syncpark commented on src/ingest/network.rs
> +            // post_body is not displayed
Display된 내용은 REconverge가 Training 할 때 사용하기 때문에 모든 필드를 출력해야 합니다.
필드 구분자로 TAB('\t')를 사용하기 때문에 Body 내용에서 '\t'를 ' '(Space)로 수정이 필요합니다.

2023-11-22 17:45 UTC, jknpark commented on src/ingest/network.rs
> +            // post_body is not displayed
Hex로 출력해도 괜찮은가요? 아니면 문자로 출력을 해야 하나요?

2023-11-23 02:07 UTC, syncpark commented on src/ingest/network.rs
> +            // post_body is not displayed
문자로 출력해야 합니다. Hex 값이면 Training이나 Analyzing할 때 토큰 추출 같은 작업이 어렵습니다.

2023-11-24 01:01 UTC, syncpark approved these changes

2023-11-24 01:01 UTC, merged